### ISSUE TITLE
series/title should not be an Array

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-data-iho#3]
@ronaldtse @opoudjis 
In the `b-11.yaml` there is `series` element with multiple titles:
https://github.com/relaton/relaton-data-iho/blob/b0c90279926ac05b61d3c1d2c56dc325e03aabce/data/b-11.yaml#L68-L79
but the grammar allows only one title:
```
series = element series {
  attribute type { SeriesType }?,
  (formattedref |
  (btitle, bplace?, seriesorganization?,
  abbreviation?,
  seriesfrom?, seriesto?,
  seriesnumber?, seriespartnumber?, seriesrun?))
}
```
Should we change grammar?

**Comment by opoudjis** [comment]
We should, but I'm trying to preserve the fact that these are in truth the one string with language variants.

Right now we have:

````
LocalizedStringOrXsAny =
  # multiple languages and scripts possible: comma delimit them if so
  attribute language { text }?,
  attribute script { text }?,
  ( text | AnyElement )+
````

I propose we add the alternative:

````
LocalizedStringOrXsAny1 =
  # multiple languages and scripts possible: comma delimit them if so
  attribute language { text }?,
  attribute script { text }?,
  ( text | AnyElement )+

LocalizedStringOrXsAny = 
  LocalizedStringOrXsAny1 | 
  element variant { LocalizedStringOrXsAny1 }+
````

So that would continue to allow the encodings:

````
<title lang="en" script="Latn" type="original">Bathymetric Publications</title>
<title lang="fr" script="Latn" type="original">Publications bathymétriques</title>
````

But if the same title is being given in two languages, we should use instead:

````
<title type="original">
  <variant lang="en" script="Latn">Bathymetric Publications</variant>
  <variant lang="fr" script="Latn">Publications bathymétriques</variant>
</title>
````

I would have to do some refactoring to use this in Metanorma, but the latter encoding is much more accurate than having two titles; and where multiple titles are allowed in the grammar, having two titles differentiated by language is still legal.

@ronaldtse What do you think?

**Comment by ronaldtse** [comment]
Agree with @opoudjis . Thanks!

**Comment by opoudjis** [comment]
Done
